# Generated by Django 3.2.12 on 2022-03-27 18:37

from django.db import migrations, models
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('sex', models.CharField(default='', max_length=2)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(default='', max_length=11)),
                ('password', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=10, null=True)),
                ('NiN', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('token', models.CharField(default='', max_length=255)),
                ('activatedBy', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('Voter', 'Voter'), ('Staff', 'Staff'), ('Candidate', 'Candidate')], default='Voter', max_length=200)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
